Simple TreeView example
filcuc/dqml pull request #14
Opened 2017-04-16 19:01 UTC by drug007

Depends on  filcuc/DOtherSide#60

2017-04-16 21:00 UTC, drug007 commented
it fails because is building against old version of DOtherSide.

2017-04-16 21:05 UTC, filcuc commented
Fine i will review it asap but seems already ok

Il 16 apr 2017 23:00, "drug007" <notifications@github.com> ha scritto:

> it fails because is building against old version of DOtherSide.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/filcuc/dqml/pull/14#issuecomment-294374018>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AG07o22Yuy1Rocvg4vaYttPfNxfrcC9lks5rwoF3gaJpZM4M-s2d>
> .
>

2017-04-22 14:07 UTC, filcuc commented on examples/simpletreeview/dub.json
> +    "copyFiles": ["source/app.qml"],
Add default.txt do copyFiles otherwise the application throws an exception and exit :)

2017-04-22 14:08 UTC, filcuc commented on examples/simpletreeview/source/custom_type.d
> +	@QtSlot()
Give a look and the indentation is seems a little bit messy

2017-04-22 14:09 UTC, filcuc commented on examples/simpletreeview/source/custom_type.d
> +        {
like here..

2017-04-22 14:09 UTC, filcuc commented on examples/simpletreeview/source/treemodel.d
> +    //QVariant headerData(int section, Qt::Orientation orientation,
Remove commented code

2017-04-22 14:10 UTC, filcuc requested changes
Except the missing addition of "default.txt" do copyFiles. Everything it's ok. I would prefear indentation to be fixed before merging :).
Thank you great work

2017-04-22 14:25 UTC, drug007 commented
@filcuc FYI now I try to used [dstep](https://github.com/jacob-carlborg/dstep) for getting class name and its members.

2017-04-22 14:27 UTC, drug007 commented
Sorry that the diff happens so large - I just changed indentation to tab only.

2017-04-22 14:31 UTC, filcuc commented
@drug007 mind to share for what purpose are you using dstep?

2017-04-22 14:33 UTC, drug007 commented
To get AST for c++ files.

2017-04-22 14:35 UTC, merged